name: columnar-data-analysis-codas-hep-2023
channels:
  - conda-forge
dependencies:
  - python==3.9.13
  - numpy==1.22.4
  - matplotlib==3.5.2
  - numexpr==2.8.3
  - numba==0.55.2
  - jax==0.3.10
  - jaxlib==0.3.10
  - xrootd==5.4.2
  - root==6.26.0
  - zstandard==0.18.0
  - zstd==1.5.2
  - lz4==4.0.0
  - python-xxhash==3.0.0
  - dask==2022.7.0
  - python-graphviz==0.20
  - pyarrow==8.0.0
  - pandas==1.4.3
  - pip==22.2
  - pip:
      - uproot==5.0.0rc1
      - awkward==1.9.0rc10
      - vector==0.8.5
      - hist[plot]==2.6.1
      - particle==0.20.1
