name: columnar-data-analysis-codas-hep-2023
channels:
  - conda-forge
dependencies:
  - awkward==2.3.1
  - dask-awkward==2023.7.0
  - dask==2023.07.0
  - h5py 
  - hist==2.6.3 
  - jax==0.4.12
  - jaxlib==0.4.12
  - jupyterlab==3.6.4
  - jupyterlab-deck==0.1.3
  - jupyterlab-mathjax3==4.3.0
  - lz4==4.3.2
  - matplotlib==3.7.1
  - numba==0.57.0
  - numexpr==2.8.4
  - numpy==1.24.3
  - pandas==2.0.3
  - pip==22
  - pyarrow==12.0.0
  - python-graphviz==0.20.1
  - python-xxhash==3.2.0
  - python==3.10
  - root==6.28.0
  - uproot==5.0.10
  - xrootd==5.5.3
  - zstandard==0.18.0
  - zstd==1.5.2
  - pip:
      - particle==0.23.0
      - vector==1.1.0
